[tools]
prek = "latest"
python = "3.14.1"

[env]
_.python.venv = { path = ".venv", create = true }

[tasks.setup]
sources = ["pyproject.toml", "uv.lock"]
run = [
  "uv sync --active",
  "prek install",
]

[tasks.test]
depends = ["setup"]
run = "tox"

[tasks.lint]
run = "prek run --all-files"
